version: "3"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - sql-data:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TokyoJoe138!
    ports:
      - 1433:1433

volumes:
  sql-data: